// Generated by CoffeeScript 1.10.0
var Promise, eachSeries, mapSeries, waterfall;

Promise = require('es6-promise').Promise;

eachSeries = function(arr, f) {
  return arr.reduce(function(promise, item) {
    return promise.then(function() {
      return f(item);
    });
  }, Promise.resolve());
};

mapSeries = function(arr, f) {
  return arr.reduce(function(promise, item) {
    return promise.then(function(results) {
      return results.concat([f(item)]);
    });
  }, Promise.resolve([]));
};

waterfall = function(fs) {
  return fs.reduce((function(_this) {
    return function(promise, f) {
      return promise.then(a.bind(_this));
    };
  })(this), Promise.resolve());
};

module.exports.eachSeries = eachSeries;

module.exports.mapSeries = mapSeries;

module.exports.waterfall = waterfall;
