// Generated by CoffeeScript 1.10.0
var CLI, commander, fs, kraken;

fs = require('fs');

commander = require('commander-b');

kraken = require('./');

module.exports = CLI = (function() {
  function CLI() {}

  CLI.prototype.run = function() {
    var pkg;
    pkg = fs.readFileSync(__dirname + '/../package.json');
    return commander('kraken').version(JSON.parse(pkg).version).action(function() {
      return kraken();
    }).execute();
  };

  return CLI;

})();
